# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sf/substreams/v1/clock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sf/substreams/v1/clock.proto',
  package='sf.substreams.v1',
  syntax='proto3',
  serialized_options=_b('ZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreams'),
  serialized_pb=_b('\n\x1csf/substreams/v1/clock.proto\x12\x10sf.substreams.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n\x05\x43lock\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06number\x18\x02 \x01(\x04R\x06number\x12\x38\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimestampBFZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreamsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CLOCK = _descriptor.Descriptor(
  name='Clock',
  full_name='sf.substreams.v1.Clock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sf.substreams.v1.Clock.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='sf.substreams.v1.Clock.number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='number', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sf.substreams.v1.Clock.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='timestamp', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=188,
)

_CLOCK.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Clock'] = _CLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Clock = _reflection.GeneratedProtocolMessageType('Clock', (_message.Message,), {
  'DESCRIPTOR' : _CLOCK,
  '__module__' : 'sf.substreams.v1.clock_pb2'
  # @@protoc_insertion_point(class_scope:sf.substreams.v1.Clock)
  })
_sym_db.RegisterMessage(Clock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
