# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erc721.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='erc721.proto',
  package='eth.erc721.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x65rc721.proto\x12\reth.erc721.v1\"7\n\tTransfers\x12*\n\ttransfers\x18\x01 \x03(\x0b\x32\x17.eth.erc721.v1.Transfer\"k\n\x08Transfer\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x0c\x12\n\n\x02to\x18\x02 \x01(\x0c\x12\x10\n\x08token_id\x18\x03 \x01(\x04\x12\x10\n\x08trx_hash\x18\x04 \x01(\x0c\x12\x0f\n\x07ordinal\x18\x05 \x01(\x04\x12\x10\n\x08\x63ontract\x18\x06 \x01(\x0c\x62\x06proto3')
)




_TRANSFERS = _descriptor.Descriptor(
  name='Transfers',
  full_name='eth.erc721.v1.Transfers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transfers', full_name='eth.erc721.v1.Transfers.transfers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=86,
)


_TRANSFER = _descriptor.Descriptor(
  name='Transfer',
  full_name='eth.erc721.v1.Transfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='eth.erc721.v1.Transfer.from', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='eth.erc721.v1.Transfer.to', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token_id', full_name='eth.erc721.v1.Transfer.token_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trx_hash', full_name='eth.erc721.v1.Transfer.trx_hash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ordinal', full_name='eth.erc721.v1.Transfer.ordinal', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract', full_name='eth.erc721.v1.Transfer.contract', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=195,
)

_TRANSFERS.fields_by_name['transfers'].message_type = _TRANSFER
DESCRIPTOR.message_types_by_name['Transfers'] = _TRANSFERS
DESCRIPTOR.message_types_by_name['Transfer'] = _TRANSFER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transfers = _reflection.GeneratedProtocolMessageType('Transfers', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERS,
  '__module__' : 'erc721_pb2'
  # @@protoc_insertion_point(class_scope:eth.erc721.v1.Transfers)
  })
_sym_db.RegisterMessage(Transfers)

Transfer = _reflection.GeneratedProtocolMessageType('Transfer', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFER,
  '__module__' : 'erc721_pb2'
  # @@protoc_insertion_point(class_scope:eth.erc721.v1.Transfer)
  })
_sym_db.RegisterMessage(Transfer)


# @@protoc_insertion_point(module_scope)
