# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sf/substreams/v1/package.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from sf.substreams.v1 import modules_pb2 as sf_dot_substreams_dot_v1_dot_modules__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sf/substreams/v1/package.proto',
  package='sf.substreams.v1',
  syntax='proto3',
  serialized_options=_b('ZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreams'),
  serialized_pb=_b('\n\x1esf/substreams/v1/package.proto\x12\x10sf.substreams.v1\x1a google/protobuf/descriptor.proto\x1a\x1esf/substreams/v1/modules.proto\"\xba\x02\n\x07Package\x12\x45\n\x0bproto_files\x18\x01 \x03(\x0b\x32$.google.protobuf.FileDescriptorProtoR\nprotoFiles\x12\x18\n\x07version\x18\x05 \x01(\x04R\x07version\x12\x33\n\x07modules\x18\x06 \x01(\x0b\x32\x19.sf.substreams.v1.ModulesR\x07modules\x12\x41\n\x0bmodule_meta\x18\x07 \x03(\x0b\x32 .sf.substreams.v1.ModuleMetadataR\nmoduleMeta\x12\x44\n\x0cpackage_meta\x18\x08 \x03(\x0b\x32!.sf.substreams.v1.PackageMetadataR\x0bpackageMetaJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\"c\n\x0fPackageMetadata\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n\x03\x64oc\x18\x04 \x01(\tR\x03\x64oc\"G\n\x0eModuleMetadata\x12#\n\rpackage_index\x18\x01 \x01(\x04R\x0cpackageIndex\x12\x10\n\x03\x64oc\x18\x02 \x01(\tR\x03\x64ocBFZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreamsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,sf_dot_substreams_dot_v1_dot_modules__pb2.DESCRIPTOR,])




_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='sf.substreams.v1.Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_files', full_name='sf.substreams.v1.Package.proto_files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='protoFiles', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='sf.substreams.v1.Package.version', index=1,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='version', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modules', full_name='sf.substreams.v1.Package.modules', index=2,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='modules', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module_meta', full_name='sf.substreams.v1.Package.module_meta', index=3,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='moduleMeta', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_meta', full_name='sf.substreams.v1.Package.package_meta', index=4,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='packageMeta', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=433,
)


_PACKAGEMETADATA = _descriptor.Descriptor(
  name='PackageMetadata',
  full_name='sf.substreams.v1.PackageMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='sf.substreams.v1.PackageMetadata.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='version', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='sf.substreams.v1.PackageMetadata.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='url', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='sf.substreams.v1.PackageMetadata.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doc', full_name='sf.substreams.v1.PackageMetadata.doc', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='doc', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=534,
)


_MODULEMETADATA = _descriptor.Descriptor(
  name='ModuleMetadata',
  full_name='sf.substreams.v1.ModuleMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_index', full_name='sf.substreams.v1.ModuleMetadata.package_index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='packageIndex', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doc', full_name='sf.substreams.v1.ModuleMetadata.doc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='doc', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=607,
)

_PACKAGE.fields_by_name['proto_files'].message_type = google_dot_protobuf_dot_descriptor__pb2._FILEDESCRIPTORPROTO
_PACKAGE.fields_by_name['modules'].message_type = sf_dot_substreams_dot_v1_dot_modules__pb2._MODULES
_PACKAGE.fields_by_name['module_meta'].message_type = _MODULEMETADATA
_PACKAGE.fields_by_name['package_meta'].message_type = _PACKAGEMETADATA
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE
DESCRIPTOR.message_types_by_name['PackageMetadata'] = _PACKAGEMETADATA
DESCRIPTOR.message_types_by_name['ModuleMetadata'] = _MODULEMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGE,
  '__module__' : 'sf.substreams.v1.package_pb2'
  # @@protoc_insertion_point(class_scope:sf.substreams.v1.Package)
  })
_sym_db.RegisterMessage(Package)

PackageMetadata = _reflection.GeneratedProtocolMessageType('PackageMetadata', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGEMETADATA,
  '__module__' : 'sf.substreams.v1.package_pb2'
  # @@protoc_insertion_point(class_scope:sf.substreams.v1.PackageMetadata)
  })
_sym_db.RegisterMessage(PackageMetadata)

ModuleMetadata = _reflection.GeneratedProtocolMessageType('ModuleMetadata', (_message.Message,), {
  'DESCRIPTOR' : _MODULEMETADATA,
  '__module__' : 'sf.substreams.v1.package_pb2'
  # @@protoc_insertion_point(class_scope:sf.substreams.v1.ModuleMetadata)
  })
_sym_db.RegisterMessage(ModuleMetadata)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
